# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='Изменено')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Создано')),
                ('serial', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заводской номер')),
                ('inventory_number', models.IntegerField(blank=True, null=True, verbose_name='Инвентарный номер')),
                ('state', models.CharField(choices=[('un', 'Неопределено'), ('ok', 'Исправен'), ('rp', 'В ремонте'), ('rv', 'В резерве'), ('cs', 'В консервации'), ('wt', 'Ожидается поступление'), ('rm', 'Ожидается списание')], default='un', max_length=2, verbose_name='Состояние')),
                ('last_check_date', models.DateField(null=True, verbose_name='Дата последней проверки')),
                ('last_repair_date', models.DateField(blank=True, null=True, verbose_name='Дата последней починки')),
                ('repair_description', models.TextField(blank=True, null=True, verbose_name='Описание починки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Измерительный прибор',
                'verbose_name_plural': 'Измерительние приборы',
            },
        ),
        migrations.CreateModel(
            name='MeasuringInstrumentKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='Изменено')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Создано')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид измерительного прибора',
                'verbose_name_plural': 'Виды измерительных приборов',
            },
        ),
        migrations.CreateModel(
            name='MeasuringInstrumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='Изменено')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Создано')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
                ('accuracy_class', models.CharField(blank=True, max_length=16, null=True, verbose_name='Класс точности')),
                ('measurement_limits', models.CharField(blank=True, max_length=64, null=True, verbose_name='Пределы измерений')),
                ('check_periodicity', models.DurationField(default=datetime.timedelta(365), verbose_name='Периодичность проверки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип измерительного прибора',
                'verbose_name_plural': 'Типы измерительных приборов',
            },
        ),
    ]
