# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='Изменено')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Создано')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='Изменено')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Создано')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Dialog', verbose_name='Дилог')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
